import {mkdir,writeFile,cp} from 'node:fs/promises';
import {pages} from '../src/pages.mjs';
import {header,footer,escape,contactDialog} from '../src/components.mjs';
import {company} from '../src/content.mjs';
import {publication} from '../src/publication.mjs';
const origin=process.env.SITE_ORIGIN || publication.origin;
if(origin && !/^https:\/\/[a-z0-9.-]+(?::\d+)?$/i.test(origin))throw new Error('SITE_ORIGIN must be an HTTPS origin without a trailing slash');
const previewEnvironment=process.env.VERCEL_ENV && process.env.VERCEL_ENV!=='production';
const production=!previewEnvironment && (process.env.SITE_STAGE || publication.stage)==='production';
if(production&&!origin)throw new Error('Production requires SITE_ORIGIN');
await mkdir('dist',{recursive:true});
await cp('public','dist',{recursive:true});
function document(page){const title=page.title+' | '+company.name;const url=origin+page.path;return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(page.description)}"><meta name="robots" content="${production?'index,follow':'noindex,nofollow'}"><meta name="theme-color" content="#102b39"><meta property="og:type" content="website"><meta property="og:locale" content="tr_TR"><meta property="og:site_name" content="${escape(company.name)}"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(page.description)}">${origin?`<link rel="canonical" href="${url}"><meta property="og:url" content="${url}">`:''}<meta name="twitter:card" content="summary"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><script src="/site.js" defer></script><script src="/contact.js" type="module"></script>${page.path==='/'?'<link rel="preload" as="image" href="/assets/quality-consulting.webp"><script src="/hero.js" defer></script>':''}<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'Organization',name:company.name,...(origin?{url:origin}:{}),address:{'@type':'PostalAddress',streetAddress:'Söğütözü Mahallesi, 9 Eylül Cad. No: 4 İç Kapı No: 1',addressLocality:'Ankara',addressCountry:'TR'}}).replaceAll('<','\\u003c')}</script></head><body>${header(page.path)}<main id="main">${page.body()}</main>${footer()}${contactDialog()}</body></html>`;}
for(const page of pages){await mkdir('dist'+page.path,{recursive:true});await writeFile('dist'+page.path+'index.html',document(page));}
await writeFile('dist/404.html',document({path:'/404/',title:'Sayfa bulunamadı',description:'Aradığınız sayfa bulunamadı.',body:()=>'<section class="not-found container"><p class="eyebrow">404</p><h1>Sayfa bulunamadı.</h1><p>Aradığınız sayfa taşınmış olabilir.</p><a class="button" href="/">Ana sayfaya dön</a></section>'}));
await writeFile('dist/robots.txt',production?`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`:'User-agent: *\nDisallow: /\n');
await writeFile('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${origin?pages.map(p=>`<url><loc>${origin+p.path}</loc></url>`).join(''):''}</urlset>`);
await writeFile('dist/_headers',`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n  Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self' https://formsubmit.co; form-action 'self' https://formsubmit.co; font-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'self'\n${production?'':'  X-Robots-Tag: noindex, nofollow\n'}`);
console.log(`Built ${pages.length} pages; stage=${production?'production':'private review'}.`);
