const slides = [
 {image:'quality-consulting.webp',alt:'Kuruluşlara yönelik danışmanlık çalışmalarını temsil eden ekip toplantısı',title:'ISO/IEC 17020',detail:'Muayene kuruluşları için danışmanlık ve 2026 sürümüne geçiş'},
 {image:'technical-training.webp',alt:'Teknik eğitim çalışmalarını temsil eden uygulamalı eğitim ortamı',title:'Bilgiden uygulamaya',detail:'Kuruluşunuzun ihtiyaçlarına göre planlanan eğitimler'},
 {image:'digital-workflow.webp',alt:'Doküman ve süreç takibini temsil eden dijital çalışma ortamı',title:'İzlenebilir süreçler',detail:'Kalite süreçlerini destekleyen yazılım çözümleri'}
];

export const heroSlides = () => `<div class="hero-visual" id="hero-slides" aria-roledescription="slayt gösterisi" aria-label="Çalışma alanlarımız">
 ${slides.map((s,i)=>`<div class="hero-slide ${i===0?'is-active':''}" role="group" aria-roledescription="slayt" aria-label="${i+1} / ${slides.length}: ${s.title}" aria-hidden="${i!==0}"><img src="/assets/${s.image}" alt="${s.alt}" width="1536" height="1024" ${i===0?'fetchpriority="high"':'loading="lazy"'}><div class="hero-image-label"><span>ÇALIŞMA ALANLARIMIZ</span><strong>${s.title}</strong><span>${s.detail}</span></div></div>`).join('')}
 </div><button class="hero-arrow hero-arrow--previous" type="button" aria-label="Önceki görsel" aria-controls="hero-slides" data-hero-step="-1" hidden><svg viewBox="0 0 24 24" width="24" height="24" fill="none" aria-hidden="true"><path d="m14 5-7 7 7 7" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg></button><button class="hero-arrow hero-arrow--next" type="button" aria-label="Sonraki görsel" aria-controls="hero-slides" data-hero-step="1" hidden><svg viewBox="0 0 24 24" width="24" height="24" fill="none" aria-hidden="true"><path d="m10 5 7 7-7 7" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg></button><p class="visually-hidden" id="hero-status" role="status" aria-live="polite" aria-atomic="true"></p>`;
