import {company,services,trainings,approach,steps} from './content.mjs';
import {consulting,certifications} from './catalog.mjs';
import {button,heading,pageHero,cta,disclaimer} from './components.mjs';
const list=items=>`<ul class="check-list">${items.map(s=>`<li>${s}</li>`).join('')}</ul>`;
const homeServices = [
 {path:'/danismanlik/',image:'quality-consulting.webp',label:'DANIŞMANLIK',title:'Standartlar ve uygunluk süreçleri',description:'Laboratuvarlar, muayene ve personel belgelendirme kuruluşları, tıbbi cihazlar, GMP, GLP ve TSE süreçleri.'},
 {path:'/egitim/',image:'technical-training.webp',label:'EĞİTİM',title:'Bilgiden uygulamaya eğitimler',description:'Yönetim sistemleri, laboratuvar uygulamaları, tıbbi cihazlar, risk yönetimi ve süreç iyileştirme eğitimleri.'},
 {path:'/belgelendirme/',image:'certification-review.webp',label:'BELGELENDİRME',title:'Yönetim sistemleri belgelendirme',description:'Kalite, çevre, iş sağlığı ve güvenliği, bilgi güvenliği ve gıda güvenliği yönetim sistemleri.'}
];
const serviceCards=()=>`<div class="grid three">${homeServices.map((s,i)=>`<a class="service-card" href="${s.path}"><div class="card-image image-${i}"><img src="/assets/${s.image}" alt="" loading="lazy" width="1536" height="1024"><span>0${i+1}</span></div><div class="card-body"><p class="eyebrow">${s.label}</p><h3>${s.title}</h3><p>${s.description}</p><span class="text-link">Hizmetleri inceleyin </span></div></a>`).join('')}</div>`;
const trainingCards=(all=false)=>`<div class="grid ${all?'two':'three'}">${trainings.map(([title,desc],i)=>({title,desc,i})).filter(({i})=>all||[0,7,9].includes(i)).map(({title,desc,i},position)=>`<${all?'article':'a'} class="training-card" ${all?`id="egitim-${i+1}"`:`href="/egitim/#egitim-${i+1}"`}><span class="course-number">${String(all?i+1:position+1).padStart(2,'0')}</span><div><h3>${title}</h3><p>${desc}</p>${!all?`<span class="text-link">Eğitimi inceleyin </span>`:''}</div></${all?'article':'a'}>`).join('')}</div>`;
const iso17025Details=()=>`${services.map(s=>`<details class="catalog-subsection" id="${s.id}"><summary><h4>${s.title}</h4></summary><div><p>${s.short}</p>${list(s.items)}</div></details>`).join('')}<details class="catalog-subsection"><summary><h4>Proje süreci</h4></summary><div><ol class="catalog-steps">${steps.map(([title,desc])=>`<li><h5>${title}</h5><p>${desc}</p></li>`).join('')}</ol></div></details><details class="catalog-subsection"><summary><h4>Proje hakkında sık sorulan sorular</h4></summary><div><h5>ISO/IEC 17025 proje süresi nasıl belirlenir?</h5><p>Proje takvimi; laboratuvarın hazırlık hızı, kapsamın büyüklüğü, metot sayısı, cihaz ve kalibrasyon durumu, yeterlilik testi / laboratuvarlar arası karşılaştırma gereklilikleri ve TÜRKAK planlamasına bağlı olarak değişebilir.</p><h5>Akreditasyon başvurusu ne zaman hazırlanır?</h5><p>Yönetim sistemi ve teknik uygulamaların başvuru için yeterli olgunluğa ulaştığı BMS ve müşteri tarafından birlikte değerlendirildikten sonra başvuru hazırlanır. Güncel TÜRKAK formları, rehberleri ve ek belge talepleri başvuru tarihinde kontrol edilir.</p><h5>Resmî ücretler hizmet kapsamına dahil midir?</h5><p>TÜRKAK ve diğer resmî kurumların başvuru, inceleme, değerlendirme ve akreditasyon ücretleri danışmanlık hizmet bedeline dahil değildir; müşteri tarafından ayrıca karşılanır.</p></div></details>${disclaimer()}`;
const consultingCatalog=()=>`<div class="grid two consulting-catalog">${consulting.map(s=>`<details class="catalog-entry" id="${s.id}"><summary><span class="catalog-code">${s.code}</span><h3>${s.title}</h3></summary><div class="catalog-content"><p>${s.description}</p>${s.items?list(s.items):''}${s.id==='iso-17025'?iso17025Details():''}</div></details>`).join('')}</div>`;
const certificationCards=()=>`<div class="grid two certification-grid">${certifications.map(s=>`<article class="certification-card" id="${s.id}"><p class="eyebrow">${s.code}</p><h2>${s.title}</h2></article>`).join('')}</div>`;
const approachGrid=()=>`<div class="grid three approach-grid">${approach.map(([title,desc],i)=>`<article><span class="number">0${i+1}</span><h3>${title}</h3><p>${desc}</p></article>`).join('')}</div>`;
const process=(items=steps)=>`<ol class="process">${items.map(([title,desc],i)=>`<li><span>0${i+1}</span><h3>${title}</h3><p>${desc}</p></li>`).join('')}</ol>`;
const generalSteps = [
 ['Kapsam ve planlama','Kuruluşun faaliyetleri ve hizmet ihtiyacı değerlendirilir; çalışma kapsamı birlikte belirlenir.'],
 ['Eğitim ve sistem çalışmaları','İlgili hizmete göre eğitim, yönetim sistemi, dokümantasyon ve uygulama çalışmaları ele alınır.'],
 ['Başvuru ve denetim hazırlığı','Hizmet kapsamında yer alan başvuru dosyaları, teknik kayıtlar ve denetim hazırlıkları üzerinde çalışılır.'],
 ['Takip ve iyileştirme','İlgili süreçte ortaya çıkan uygunsuzluklar ve düzeltici faaliyet çalışmalarına destek verilir.']
];
export const pages = [
 {path:'/',title:'Danışmanlık, Eğitim ve Belgelendirme',description:'BMS Kalite Yazılım A.Ş.: yönetim sistemleri, laboratuvarlar, tıbbi cihazlar, GMP, GLP ve TSE alanlarında danışmanlık, eğitim ve belgelendirme hizmetleri.',body:()=>`
 <section class="hero">
  <div class="container hero-grid">
   <div class="hero-copy">
    <p class="eyebrow">KALİTE · AKREDİTASYON · TEKNOLOJİ</p>
    <h1>Kaliteye<br>odaklanın.<br><span>Güvenle ilerleyin.</span></h1>
    <p class="hero-description">Kuruluşunuz için yönetim sistemleri, akreditasyon, tıbbi cihazlar ve kalite süreçlerinde danışmanlık, eğitim ve belgelendirme hizmetleri.</p>
    <div class="buttons">${button('Hizmetlerimizi keşfedin','/danismanlik/')}<a class="hero-text-link" href="/egitim/">Eğitim programları </a></div>
    <div class="hero-caption"><span class="caption-rule"></span><span>Kuruluşa özel yaklaşım.<br>Uygulanabilir, sürdürülebilir çözümler.</span></div>
   </div>
   <div class="hero-visual">
    <img src="/assets/laboratory-architecture.webp" alt="Analitik laboratuvar ortamını temsil eden özgün görsel" width="1536" height="1024" fetchpriority="high">
    <div class="hero-image-label"><span>ÇALIŞMA ALANLARIMIZ</span><strong>Kalite ve uygunluk</strong><span>Yönetim sistemleri · Laboratuvarlar · Tıbbi cihazlar</span></div>
    <div class="hero-image-index" aria-hidden="true">BMS / KALİTE YAZILIM</div>
   </div>
  </div>
 </section>
 <div class="expertise-bar"><div class="container quick-links"><a href="/danismanlik/"><span>01</span><div><h2>Danışmanlık</h2><p>Standarttan uygulamaya</p></div></a><a href="/egitim/"><span>02</span><div><h2>Eğitim</h2><p>Bilgiden yetkinliğe</p></div></a><a href="/belgelendirme/"><span>03</span><div><h2>Belgelendirme</h2><p>Yönetim sistemleri</p></div></a></div></div>
 <section class="section"><div class="container about-grid"><div class="about-visual"><img src="/assets/scientific-workspace.webp" alt="Bilimsel bir çalışma ortamında iş birliğini temsil eden görsel" width="1536" height="1024" loading="lazy"><div class="standard-badge"><span class="badge-label">YAKLAŞIMIMIZ</span><strong>Kaliteyi birlikte<br>geliştiriyoruz.</strong></div></div><div><p class="eyebrow">HAKKIMIZDA</p><h2>Kalite ve teknolojiyi<br>bir araya getiriyoruz.</h2><p>${company.intro}</p><p>Yönetim sistemleri, laboratuvarlar, muayene ve personel belgelendirme kuruluşları, tıbbi cihazlar, GMP, GLP ve TSE süreçlerinde danışmanlık sunuyoruz. Eğitim, yönetim sistemleri belgelendirme hizmetleri ve kalite süreçlerini destekleyen yazılım çözümleriyle çalışmalarımızı tamamlıyoruz.</p>${button('BMS’yi tanıyın','/hakkimizda/',true)}</div></div></section>
 <section class="section pale"><div class="container">${heading('HİZMETLERİMİZ','Standarttan uygulamaya,<br>her aşamada destek.','Kuruluşların kalite ve uygunluk ihtiyaçları için danışmanlık, eğitim ve belgelendirme hizmetleri.')}${serviceCards()}</div></section>
 <section class="section education-section"><div class="container education-layout"><div class="education-intro">${heading('EĞİTİM HİZMETLERİ','Bilgiyi uygulamaya<br>dönüştürün.','Yönetim sistemlerinden teknik uygulamalara, kuruluşun faaliyet alanına göre planlanan eğitimler.')}${button('Tüm eğitimler','/egitim/',true)}<p class="small-note">Eğitimlerin kesin kapsamı, katılımcı sayısı ve süreleri proje başlangıcında netleştirilir.</p></div><div class="education-courses">${trainingCards()}</div></div></section>
 <section class="section navy"><div class="container principles-layout">${heading('NEDEN BMS?','Kuruluşunuza özel.<br>Uygulamaya dönük.')}${approachGrid()}</div></section>
 <section class="section"><div class="container">${heading('ÇALIŞMA YAKLAŞIMIMIZ','İhtiyaçtan uygulamaya,<br>planlı bir çalışma.')}${process(generalSteps)}</div></section>
 <section class="software-strip"><div class="container about-grid"><div><p class="eyebrow">KALİTE YAZILIMLARI</p><h2>İzlenebilir süreçler.<br>Sürdürülebilir iş akışları.</h2></div><div><p>Doküman, kayıt, takip ve raporlama ihtiyaçlarını, uygun olduğunda yazılım destekli iş akışlarıyla ele alıyoruz.</p>${button('Dijitalleşme yaklaşımımız','/yazilim/',true)}</div></div></section>${cta()}`},
 {path:'/hakkimizda/',title:'Hakkımızda',description:'BMS Kalite Yazılım A.Ş., LHUSTEK bünyesinde sağlık, teknoloji ve kalite odaklı danışmanlık, eğitim, belgelendirme ve yazılım hizmetleri sunar.',body:()=>`${pageHero('Hakkımızda','Kalite, sağlık ve teknoloji<br>aynı çatı altında.','Uygulanabilir, sürdürülebilir ve ihtiyaçlara özel çözümler.')}<section class="section"><div class="container about-grid"><div class="about-visual"><img src="/assets/scientific-workspace.webp" alt="Bilimsel bir çalışma ortamında iş birliğini temsil eden görsel" width="1536" height="1024"></div><div><h2>BMS Kalite Yazılım A.Ş.</h2><p>${company.intro}</p><p>Yönetim sistemleri, laboratuvarlar, muayene ve personel belgelendirme kuruluşları, tıbbi cihazlar, GMP, GLP ve TSE süreçlerinde danışmanlık sunuyoruz. Eğitim, yönetim sistemleri belgelendirme hizmetleri ve kalite süreçlerini destekleyen yazılım çözümleriyle çalışmalarımızı tamamlıyoruz.</p></div></div><div class="container grid two values"><article><p class="eyebrow">MİSYONUMUZ</p><h2>İhtiyaçlara özel çözümler.</h2><p>${company.mission}</p></article><article><p class="eyebrow">VİZYONUMUZ</p><h2>Sürdürülebilir bir kalite anlayışı.</h2><p>${company.vision}</p></article></div></section><section class="section pale"><div class="container">${heading('YAKLAŞIMIMIZ','Neden BMS?')}${approachGrid()}</div></section>${cta()}`},
 {path:'/danismanlik/',title:'Danışmanlık Hizmetleri',description:'Laboratuvar, biyobankacılık, tıbbi cihaz, bilgi güvenliği, gıda güvenliği ve enerji yönetimi alanlarında BMS danışmanlık hizmetleri.',body:()=>`${pageHero('Danışmanlık','Standartlar, kalite<br>ve uygunluk süreçleri.','Akreditasyona hazırlık, laboratuvar ve biyobankacılık, tıbbi cihazlar ve yönetim sistemleri için danışmanlık.')}<section class="section"><div class="container">${heading('DANIŞMANLIK HİZMETLERİMİZ','Kuruluşunuzun ihtiyacına<br>uygun hizmetler.')}${consultingCatalog()}</div></section>${cta()}`},
 {path:'/egitim/',title:'Yönetim Sistemleri ve Teknik Eğitimler',description:'Yönetim sistemleri, laboratuvar ve tıbbi cihaz uygulamaları, havacılık, enerji, bilgi güvenliği ve süreç iyileştirme alanlarında BMS eğitimleri.',body:()=>`${pageHero('Eğitim','Bilgiden uygulamaya,<br>mesleki yetkinlik.','Yönetim sistemleri, teknik uygulamalar, risk yönetimi ve süreç iyileştirme alanlarında eğitim programları.')}<section class="section"><div class="container">${heading('EĞİTİM HİZMETLERİMİZ','Eğitim programlarımız.')}${trainingCards(true)}<aside class="note"><strong>Kuruluşa göre planlanan eğitimler</strong><p>Eğitimlerin kapsamı, katılımcı sayısı ve süreleri kuruluşun ihtiyaçlarına göre birlikte planlanır. ISO/IEC 17025 projesi kapsamında verilen eğitimlerde katılımcılar için e-imzalı eğitim sertifikası düzenlenebilir.</p></aside></div></section>${cta()}`},
 {path:'/belgelendirme/',title:'Yönetim Sistemleri Belgelendirme Hizmetleri',description:'ISO 9001:2015, ISO 14001:2015, ISO 45001:2018, ISO 27001:2022 ve ISO 22000:2018 yönetim sistemleri belgelendirme hizmetleri.',body:()=>`${pageHero('Belgelendirme','Yönetim sistemleri<br>belgelendirme hizmetleri.','Kalite, çevre, iş sağlığı ve güvenliği, bilgi güvenliği ve gıda güvenliği alanlarında belgelendirme hizmetleri.')}<section class="section"><div class="container">${certificationCards()}</div></section>${cta()}`},
 {path:'/yazilim/',title:'Kalite Yazılımları ve Dijitalleşme',description:'Kalite süreçlerinde doküman, kayıt, takip ve raporlama ihtiyaçlarına yönelik BMS yazılım ve dijitalleşme yaklaşımı.',body:()=>`${pageHero('Kalite Yazılımları','Kalite süreçlerinde<br>dijitalleşme perspektifi.','Doküman, kayıt, takip ve raporlama ihtiyaçları için yazılım destekli, sürdürülebilir iş akışları.')}<section class="section"><div class="container"><div class="intro-narrow"><h2>İhtiyaçtan başlayan bir yaklaşım.</h2><p>BMS, kalite süreçlerini destekleyen yazılım çözümleri üzerinde çalışmaktadır. Laboratuvarın ve kuruluşun ihtiyaçları uygun olduğunda doküman, kayıt, takip ve raporlama süreçleri yazılım destekli iş akışlarıyla ele alınabilir.</p></div><div class="grid two values">${[['Doküman ve kayıt','Kalite süreçlerindeki doküman ve kayıt ihtiyaçlarının değerlendirilmesi.'],['Takip ve raporlama','İzlenebilirlik ve süreç takibi ihtiyaçlarının yazılım perspektifiyle ele alınması.']].map(([t,d])=>`<article><p class="eyebrow">DİJİTALLEŞME</p><h2>${t}</h2><p>${d}</p></article>`).join('')}</div></div></section>${cta()}`},
 {path:'/iletisim/',title:'İletişim ve Merkezimiz',description:'BMS Kalite Yazılım A.Ş. merkezi: LHUSTEK, Söğütözü Mahallesi, 9 Eylül Cad. No: 4 İç Kapı No: 1, Ankara.',body:()=>`${pageHero('İletişim','Merkezimiz Ankara’da.','BMS Kalite Yazılım A.Ş. · Lokman Hekim Üniversitesi Sağlık İlaç Teknoloji Merkezi')}<section class="section"><div class="container contact-grid"><div><p class="eyebrow">MERKEZİMİZ</p><h2>Kalite ve teknolojinin<br>buluşma noktasında.</h2><p>${company.center}</p><address>${company.address}</address>${company.email?`<p><a href="mailto:${company.email}">${company.email}</a></p>`:''}${company.phone?`<p><a href="tel:${company.phone.replace(/[^+0-9]/g,'')}">${company.phone}</a></p>`:''}<div class="buttons">${button('Haritada görüntüle','https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(company.address))}<button class="button secondary copy-address" data-address="${company.address}">Adresi kopyala</button></div><p class="copy-status" role="status" aria-live="polite"></p></div><aside class="contact-panel"><span class="location-label">ANKARA / SÖĞÜTÖZÜ</span><h2>LHUSTEK</h2><p>Lokman Hekim Üniversitesi<br>Sağlık İlaç Teknoloji Merkezi</p><div class="contact-divider"></div><p>9 Eylül Caddesi<br>No: 4 · İç Kapı No: 1</p><span class="location-label">BMS KALİTE YAZILIM A.Ş.</span></aside></div></section>`}
];
