import {company,services,trainings,approach,steps} from './content.mjs';
import {consulting,certifications} from './catalog.mjs';
import {button,heading,pageHero,cta,disclaimer,contactButton,contactForm} from './components.mjs';
import {heroSlides} from './hero.mjs';
const list=items=>`<ul class="check-list">${items.map(s=>`<li>${s}</li>`).join('')}</ul>`;
const homeServices = [
 {path:'/danismanlik/',image:'quality-consulting.webp',label:'DANIŞMANLIK',title:'Standartlar ve uygunluk süreçleri',description:'ISO/IEC 17020 muayene kuruluşları, laboratuvarlar ve personel belgelendirme kuruluşları, tıbbi cihazlar, GMP, GLP ve TSE süreçleri.'},
 {path:'/egitim/',image:'technical-training.webp',label:'EĞİTİM',title:'Bilgiden uygulamaya eğitimler',description:'Yönetim sistemleri, laboratuvar uygulamaları, tıbbi cihazlar, risk yönetimi ve süreç iyileştirme eğitimleri.'},
 {path:'/belgelendirme/',image:'certification-review.webp',label:'BELGELENDİRME DANIŞMANLIĞI',title:'Belgelendirme süreçlerine hazırlık',description:'Kalite, çevre, iş sağlığı ve güvenliği, bilgi güvenliği ve gıda güvenliği yönetim sistemleri.'}
];
const serviceCards=()=>`<div class="grid three">${homeServices.map((s,i)=>`<a class="service-card" href="${s.path}"><div class="card-image image-${i}"><img src="/assets/${s.image}" alt="" loading="lazy" width="1536" height="1024"><span>0${i+1}</span></div><div class="card-body"><p class="eyebrow">${s.label}</p><h3>${s.title}</h3><p>${s.description}</p><span class="text-link">Hizmetleri inceleyin </span></div></a>`).join('')}</div>`;
const serviceDisclosure=({id,label,title,description,subject=title,training=false})=>`<details class="service-disclosure${training?' service-disclosure--training':''}" id="${id}"><summary><span class="${training?'course-number':'eyebrow'}">${label}</span><h3>${title}</h3><p class="service-disclosure-description">${description}</p></summary><div class="service-disclosure-action">${contactButton(subject)}</div></details>`;
const trainingCards=(all=false)=>{
 const entries=trainings.map(([title,desc],i)=>({title,desc,i}));
 const ordered=all?[entries[10],entries[11],...entries.filter(({i})=>i!==10&&i!==11)]:[entries[10],entries[7],entries[9]];
 return `<div class="grid ${all?'service-disclosures training-catalog':'three'}">${ordered.map(({title,desc,i},position)=>all
  ?serviceDisclosure({id:`egitim-${i+1}`,label:String(position+1).padStart(2,'0'),title,description:desc,training:true})
  :`<a class="training-card" href="/egitim/#egitim-${i+1}"><span class="course-number">${String(position+1).padStart(2,'0')}</span><div><h3>${title}</h3><p>${desc}</p><span class="text-link">Eğitimi inceleyin</span></div></a>`).join('')}</div>`;
};
const iso17025Details=()=>`${services.map(s=>`<details class="catalog-subsection" id="${s.id}"><summary><h4>${s.title}</h4></summary><div><p>${s.short}</p>${list(s.items)}</div></details>`).join('')}<details class="catalog-subsection"><summary><h4>Proje süreci</h4></summary><div><ol class="catalog-steps">${steps.map(([title,desc])=>`<li><h5>${title}</h5><p>${desc}</p></li>`).join('')}</ol></div></details><details class="catalog-subsection"><summary><h4>Proje hakkında sık sorulan sorular</h4></summary><div><h5>ISO/IEC 17025 proje süresi nasıl belirlenir?</h5><p>Proje takvimi; laboratuvarın hazırlık hızı, kapsamın büyüklüğü, metot sayısı, cihaz ve kalibrasyon durumu, yeterlilik testi / laboratuvarlar arası karşılaştırma gereklilikleri ve TÜRKAK planlamasına bağlı olarak değişebilir.</p><h5>Akreditasyon başvurusu ne zaman hazırlanır?</h5><p>Yönetim sistemi ve teknik uygulamaların başvuru için yeterli olgunluğa ulaştığı BMS ve müşteri tarafından birlikte değerlendirildikten sonra başvuru hazırlanır. Güncel TÜRKAK formları, rehberleri ve ek belge talepleri başvuru tarihinde kontrol edilir.</p><h5>Resmî ücretler hizmet kapsamına dahil midir?</h5><p>TÜRKAK ve diğer resmî kurumların başvuru, inceleme, değerlendirme ve akreditasyon ücretleri danışmanlık hizmet bedeline dahil değildir; müşteri tarafından ayrıca karşılanır.</p></div></details>${disclaimer()}`;
const consultingCatalog=()=>`<div class="grid two consulting-catalog">${consulting.map(s=>`<details class="catalog-entry" id="${s.id}"><summary><span class="catalog-code">${s.code}</span><h3>${s.title}</h3></summary><div class="catalog-content"><p>${s.description}</p>${s.items?list(s.items):''}${contactButton(`${s.code} – ${s.title}`)}${s.id==='iso-17025'?iso17025Details():''}</div></details>`).join('')}</div>`;
const certificationCards=()=>`<div class="grid service-disclosures certification-grid">${certifications.map(s=>serviceDisclosure({id:s.id,label:s.code,title:s.title,description:`${s.code} kapsamında kuruluşunuzun belgelendirmeye hazırlık ihtiyaçlarını birlikte değerlendirelim.`,subject:`${s.code} – ${s.title}`})).join('')}</div>`;
const approachGrid=()=>`<div class="grid three approach-grid">${approach.map(([title,desc],i)=>`<article><span class="number">0${i+1}</span><h3>${title}</h3><p>${desc}</p></article>`).join('')}</div>`;
const process=(items=steps)=>`<ol class="process">${items.map(([title,desc,detail],i)=>`<li><span>0${i+1}</span><h3>${title}</h3><div>${detail?`<p class="process-lead">${desc}</p><p>${detail}</p>`:`<p>${desc}</p>`}</div></li>`).join('')}</ol>`;
const generalSteps = [
 ['Kapsam ve planlama','İhtiyacınızı analiz ediyor, size özel yol haritası oluşturuyoruz.','Mevcut durumunuzu ve hedeflerinizi değerlendirerek danışmanlık kapsamını netleştiriyor, uygulanabilir bir plan oluşturuyoruz.'],
 ['Eğitim ve sistem çalışmaları','Sisteminizi kuruyor, ekibinizi uygulamaya hazırlıyoruz.','İhtiyacınıza uygun eğitim, dokümantasyon ve sistem çalışmalarını gerçekleştirerek sürdürülebilir bir yapı oluşturuyoruz.'],
 ['Başvuru ve denetim hazırlığı','Denetime giden yolu birlikte, güvenle hazırlıyoruz.','Başvuru dosyaları, teknik kayıtlar ve dokümantasyonu gözden geçirerek eksiklikleri belirliyor ve denetim hazırlığınızı tamamlıyoruz.'],
 ['Takip ve iyileştirme','Denetim sonrasında da yanınızdayız.','Uygunsuzlukların giderilmesi, düzeltici faaliyetler ve sürekli iyileştirme çalışmalarında ihtiyaç duyduğunuz desteği sürdürüyoruz.']
];
export const pages = [
 {path:'/',title:'Danışmanlık, Eğitim ve Belgelendirme Danışmanlığı',description:'BMS Kalite Yazılım A.Ş.: yönetim sistemleri, laboratuvarlar, tıbbi cihazlar, GMP, GLP ve TSE alanlarında danışmanlık, eğitim ve belgelendirme danışmanlığı hizmetleri.',body:()=>`
 <section class="hero" aria-label="BMS hizmet alanları">
  <div class="container hero-grid">
   <div class="hero-copy">
    <p class="eyebrow">KALİTE · AKREDİTASYON · TEKNOLOJİ</p>
    <h1>Kaliteye<br>odaklanın<br><span>Güvenle ilerleyin</span></h1>
    <p class="hero-description">ISO/IEC 17020 muayene kuruluşları başta olmak üzere, yönetim sistemleri ve akreditasyon süreçlerinizde danışmanlık, eğitim ve belgelendirme danışmanlığı.</p>
    <div class="buttons">${button('ISO/IEC 17020 danışmanlığı','/danismanlik/#iso-17020')}<a class="hero-text-link" href="/danismanlik/">Tüm hizmetlerimiz</a></div>
    <div class="hero-caption"><span class="caption-rule"></span><span>Kuruluşa özel yaklaşım.<br>Uygulanabilir, sürdürülebilir çözümler.</span></div>
   </div>
   ${heroSlides()}
  </div>
 </section>
 <div class="expertise-bar"><div class="container quick-links"><a href="/danismanlik/"><div><h2>Danışmanlık</h2><p>Standarttan uygulamaya</p></div></a><a href="/egitim/"><div><h2>Eğitim</h2><p>Bilgiden yetkinliğe</p></div></a><a href="/belgelendirme/"><div><h2>Belgelendirme Danışmanlığı</h2><p>Yönetim sistemleri</p></div></a></div></div>
 <section class="section"><div class="container about-grid"><div class="about-visual"><img src="/assets/scientific-workspace.webp" alt="Bilimsel bir çalışma ortamında iş birliğini temsil eden görsel" width="1536" height="1024" loading="lazy"><div class="standard-badge"><span class="badge-label">YAKLAŞIMIMIZ</span><strong>Kaliteyi birlikte<br>geliştiriyoruz.</strong></div></div><div><p class="eyebrow">HAKKIMIZDA</p><h2>Kalite ve teknolojiyi<br>bir araya getiriyoruz.</h2><p>${company.intro}</p><p>ISO/IEC 17020 muayene kuruluşları, yönetim sistemleri, laboratuvarlar ve personel belgelendirme kuruluşları, tıbbi cihazlar, GMP, GLP ve TSE süreçlerinde danışmanlık sunuyoruz. Eğitim, yönetim sistemleri belgelendirme danışmanlığı hizmetleri ve kalite süreçlerini destekleyen yazılım çözümleriyle çalışmalarımızı tamamlıyoruz.</p>${button('BMS’yi tanıyın','/hakkimizda/',true)}</div></div></section>
 <section class="section pale"><div class="container">${heading('HİZMETLERİMİZ','Standarttan uygulamaya,<br>her aşamada destek.','Kuruluşların kalite ve uygunluk ihtiyaçları için danışmanlık, eğitim ve belgelendirme danışmanlığı hizmetleri.')}${serviceCards()}</div></section>
 <section class="section education-section"><div class="container education-layout"><div class="education-intro">${heading('EĞİTİM HİZMETLERİ','Bilgiyi uygulamaya<br>dönüştürün.','Yönetim sistemlerinden teknik uygulamalara, kuruluşun faaliyet alanına göre planlanan eğitimler.')}${button('Tüm eğitimler','/egitim/',true)}<p class="small-note">Eğitimlerin kesin kapsamı, katılımcı sayısı ve süreleri proje başlangıcında netleştirilir.</p></div><div class="education-courses">${trainingCards()}</div></div></section>
 <section class="section navy"><div class="container principles-layout">${heading('NEDEN BMS?','Kuruluşunuza özel.<br>Uygulamaya dönük.')}${approachGrid()}</div></section>
 <section class="section"><div class="container">${heading('ÇALIŞMA YAKLAŞIMIMIZ','İhtiyaçtan uygulamaya,<br>planlı bir çalışma.')}${process(generalSteps)}<p class="process-summary">Analiz ediyoruz <span aria-hidden="true">→</span> Sistemi kuruyoruz <span aria-hidden="true">→</span> Denetime hazırlıyoruz <span aria-hidden="true">→</span> Sonrasında da geliştirmeye devam ediyoruz.</p></div></section>
 <section class="software-strip"><div class="container about-grid"><div><p class="eyebrow">KALİTE YAZILIMLARI</p><h2>İzlenebilir süreçler.<br>Sürdürülebilir iş akışları.</h2></div><div><p>Doküman, kayıt, takip ve raporlama ihtiyaçlarını, uygun olduğunda yazılım destekli iş akışlarıyla ele alıyoruz.</p>${button('Dijitalleşme yaklaşımımız','/yazilim/',true)}</div></div></section>${cta()}`},
 {path:'/hakkimizda/',title:'Hakkımızda',description:'BMS Kalite Yazılım A.Ş., LHUSTEK bünyesinde sağlık, teknoloji ve kalite odaklı danışmanlık, eğitim, belgelendirme danışmanlığı ve yazılım hizmetleri sunar.',body:()=>`${pageHero('Hakkımızda','Kalite, sağlık ve teknoloji<br>aynı çatı altında.','Uygulanabilir, sürdürülebilir ve ihtiyaçlara özel çözümler.')}<section class="section"><div class="container about-grid"><div class="about-visual"><img src="/assets/scientific-workspace.webp" alt="Bilimsel bir çalışma ortamında iş birliğini temsil eden görsel" width="1536" height="1024"></div><div><h2>BMS Kalite Yazılım A.Ş.</h2><p>${company.intro}</p><p>ISO/IEC 17020 muayene kuruluşları, yönetim sistemleri, laboratuvarlar ve personel belgelendirme kuruluşları, tıbbi cihazlar, GMP, GLP ve TSE süreçlerinde danışmanlık sunuyoruz. Eğitim, yönetim sistemleri belgelendirme danışmanlığı hizmetleri ve kalite süreçlerini destekleyen yazılım çözümleriyle çalışmalarımızı tamamlıyoruz.</p></div></div><div class="container grid two values"><article><p class="eyebrow">MİSYONUMUZ</p><h2>İhtiyaçlara özel çözümler.</h2><p>${company.mission}</p></article><article><p class="eyebrow">VİZYONUMUZ</p><h2>Sürdürülebilir bir kalite anlayışı.</h2><p>${company.vision}</p></article></div></section><section class="section pale"><div class="container">${heading('YAKLAŞIMIMIZ','Neden BMS?')}${approachGrid()}</div></section>${cta()}`},
 {path:'/danismanlik/',title:'Danışmanlık Hizmetleri',description:'ISO/IEC 17020 muayene kuruluşları, laboratuvarlar ve yönetim sistemleri için BMS danışmanlığı; 2026 sürümüne geçiş ve akreditasyona hazırlık.',body:()=>`${pageHero('Danışmanlık','Standartlar, kalite<br>ve uygunluk süreçleri.','ISO/IEC 17020 muayene kuruluşları ve 2026 sürümüne geçiş başta olmak üzere; akreditasyona hazırlık, laboratuvarlar, tıbbi cihazlar ve yönetim sistemleri için danışmanlık.')}<section class="section"><div class="container">${heading('DANIŞMANLIK HİZMETLERİMİZ','Kuruluşunuzun ihtiyacına<br>uygun hizmetler.')}${consultingCatalog()}</div></section>${cta()}`},
 {path:'/egitim/',title:'Yönetim Sistemleri ve Teknik Eğitimler',description:'Yönetim sistemleri, laboratuvar ve tıbbi cihaz uygulamaları, havacılık, enerji, bilgi güvenliği ve süreç iyileştirme alanlarında BMS eğitimleri.',body:()=>`${pageHero('Eğitim','Bilgiden uygulamaya,<br>mesleki yetkinlik.','Yönetim sistemleri, teknik uygulamalar, risk yönetimi ve süreç iyileştirme alanlarında eğitim programları.')}<section class="section"><div class="container">${heading('EĞİTİM HİZMETLERİMİZ','Eğitim programlarımız.')}${trainingCards(true)}<aside class="note"><strong>Kuruluşa göre planlanan eğitimler</strong><p>Eğitimlerin kapsamı, katılımcı sayısı ve süreleri kuruluşun ihtiyaçlarına göre birlikte planlanır. ISO/IEC 17025 projesi kapsamında verilen eğitimlerde katılımcılar için e-imzalı eğitim sertifikası düzenlenebilir.</p></aside></div></section>${cta()}`},
 {path:'/belgelendirme/',title:'Yönetim Sistemleri Belgelendirme Danışmanlığı',description:'ISO 9001:2026, ISO 14001:2015, ISO 45001:2018, ISO 27001:2022 ve ISO 22000:2018 yönetim sistemleri belgelendirme danışmanlığı hizmetleri.',body:()=>`${pageHero('Belgelendirme Danışmanlığı','Yönetim sistemleri<br>belgelendirme danışmanlığı hizmetleri.','Kalite, çevre, iş sağlığı ve güvenliği, bilgi güvenliği ve gıda güvenliği alanlarında belgelendirme danışmanlığı hizmetleri.')}<section class="section"><div class="container">${heading('BELGELENDİRME DANIŞMANLIĞI','Yönetim sistemleri için<br>hazırlık ve danışmanlık.')}${certificationCards()}</div></section>${cta()}`},
 {path:'/yazilim/',title:'Kalite Yazılımları ve Dijitalleşme',description:'Kalite süreçlerinde doküman, kayıt, takip ve raporlama ihtiyaçlarına yönelik BMS yazılım ve dijitalleşme yaklaşımı.',body:()=>`${pageHero('Kalite Yazılımları','Kalite süreçlerinde<br>dijitalleşme perspektifi.','Doküman, kayıt, takip ve raporlama ihtiyaçları için yazılım destekli, sürdürülebilir iş akışları.')}<section class="section"><div class="container"><div class="intro-narrow"><h2>İhtiyaçtan başlayan bir yaklaşım.</h2><p>BMS, kalite süreçlerini destekleyen yazılım çözümleri üzerinde çalışmaktadır. Laboratuvarın ve kuruluşun ihtiyaçları uygun olduğunda doküman, kayıt, takip ve raporlama süreçleri yazılım destekli iş akışlarıyla ele alınabilir.</p></div><div class="grid two values">${[['Doküman ve kayıt','Kalite süreçlerindeki doküman ve kayıt ihtiyaçlarının değerlendirilerek zaman ve kağıt israfının önlenerek doküman izlenebilirliğinin en üst seviyeye çıkarılması.'],['Takip ve raporlama','İzlenebilirlik ve süreç takibi ihtiyaçlarının yazılım perspektifiyle ele alınarak personelden kaynaklanacak hataların minimuma indirilmesi, akreditasyon süreçlerinin hızlanması.']].map(([t,d])=>`<article><p class="eyebrow">DİJİTALLEŞME</p><h2>${t}</h2><p>${d}</p></article>`).join('')}</div></div></section>${cta()}`},
 {path:'/iletisim/',title:'İletişim ve Merkezimiz',description:'BMS Kalite Yazılım A.Ş. merkezi: LHUSTEK, Söğütözü Mahallesi, 9 Eylül Cad. No: 4 İç Kapı No: 1, Ankara.',body:()=>`${pageHero('İletişim','Merkezimiz Ankara’da.','BMS Kalite Yazılım A.Ş. · Lokman Hekim Üniversitesi Sağlık İlaç Teknoloji Merkezi')}<section class="section" id="iletisim-formu"><div class="container contact-form-layout"><div><p class="eyebrow">İLETİŞİM</p><h2>İhtiyacınızı birlikte<br>değerlendirelim.</h2><p>Danışmanlık, eğitim, belgelendirme danışmanlığı ve kalite yazılımları için talebinizi paylaşın.</p><p>Size e-posta adresiniz üzerinden dönüş yapabilmemiz için formu doldurmanız yeterli.</p></div><div class="form-card">${contactForm()}</div></div></section><section class="section pale"><div class="container contact-grid"><div><p class="eyebrow">MERKEZİMİZ</p><h2>Kalite ve teknolojinin<br>buluşma noktasında.</h2><p>${company.center}</p><address>${company.address}</address>${company.email?`<p><a href="mailto:${company.email}">${company.email}</a></p>`:''}${company.phone?`<p><a href="tel:${company.phone.replace(/[^+0-9]/g,'')}">${company.phone}</a></p>`:''}<div class="buttons">${button('Haritada görüntüle','https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(company.address))}<button class="button secondary copy-address" data-address="${company.address}">Adresi kopyala</button></div><p class="copy-status" role="status" aria-live="polite"></p></div><aside class="contact-panel"><span class="location-label">ANKARA / SÖĞÜTÖZÜ</span><h2>LHUSTEK</h2><p>Lokman Hekim Üniversitesi<br>Sağlık İlaç Teknoloji Merkezi</p><div class="contact-divider"></div><p>9 Eylül Caddesi<br>No: 4 · İç Kapı No: 1</p><span class="location-label">BMS KALİTE YAZILIM A.Ş.</span></aside></div></section>`}
];
