import {company,services,trainings,approach,steps} from './content.mjs';
import {button,heading,pageHero,cta,disclaimer,arrow} from './components.mjs';
const list=items=>`<ul class="check-list">${items.map(s=>`<li>${s}</li>`).join('')}</ul>`;
const serviceCards=()=>`<div class="grid three">${services.map((s,i)=>`<a class="service-card" href="/danismanlik/#${s.id}"><div class="card-image image-${i}"><img src="/assets/laboratory.png" alt="" loading="lazy" width="1536" height="1024"><span>0${i+1}</span></div><div class="card-body"><p class="eyebrow">ISO/IEC 17025</p><h3>${s.title}</h3><p>${s.short}</p><span class="text-link">Hizmeti inceleyin ${arrow}</span></div></a>`).join('')}</div>`;
const trainingCards=(all=false)=>`<div class="grid ${all?'two':'three'}">${trainings.slice(0,all?7:3).map(([title,desc],i)=>`<${all?'article':'a'} class="training-card" ${all?`id="egitim-${i+1}"`:`href="/egitim/#egitim-${i+1}"`}><span class="course-number">${String(i+1).padStart(2,'0')}</span><div><h3>${title}</h3><p>${desc}</p>${!all?`<span class="text-link">Eğitimi inceleyin ${arrow}</span>`:''}</div></${all?'article':'a'}>`).join('')}</div>`;
const approachGrid=()=>`<div class="grid three approach-grid">${approach.map(([title,desc],i)=>`<article><span class="number">0${i+1}</span><h3>${title}</h3><p>${desc}</p></article>`).join('')}</div>`;
const process=()=>`<ol class="process">${steps.map(([title,desc],i)=>`<li><span>0${i+1}</span><h3>${title}</h3><p>${desc}</p></li>`).join('')}</ol>`;
export const pages = [
 {path:'/',title:'ISO/IEC 17025 Danışmanlık ve Eğitim',description:'BMS Kalite Yazılım A.Ş. ile ISO/IEC 17025 yönetim sistemi, laboratuvar eğitimleri, TÜRKAK akreditasyonuna hazırlık ve kalite yazılımları.',body:()=>`
 <section class="hero"><div class="hero-photo" aria-hidden="true"></div><div class="container hero-inner"><p class="eyebrow">BMS KALİTE YAZILIM A.Ş.</p><h1>Kaliteye odaklanın.<br><span>Güvenle ilerleyin.</span></h1><p class="hero-description">Laboratuvarınız için ISO/IEC 17025 danışmanlığı,<br class="desktop-break"> eğitim ve akreditasyon hazırlığı.</p><div class="buttons">${button('Danışmanlık hizmetlerimiz','/danismanlik/')}${button('Eğitimlerimizi keşfedin','/egitim/',true)}</div><div class="hero-caption"><span class="caption-rule"></span><span>Kalite · Güvenilirlik · İzlenebilirlik</span></div></div></section>
 <section class="section"><div class="container about-grid"><div class="about-visual"><img src="/assets/laboratory.png" alt="Laboratuvar çalışmalarını temsil eden mikroskop ve cam malzemeler" width="1536" height="1024" loading="lazy"><div class="standard-badge"><strong>ISO/IEC<br>17025</strong><span>Odaklı danışmanlık</span></div></div><div><p class="eyebrow">HAKKIMIZDA</p><h2>Kalite ve teknolojiyi<br>bir araya getiriyoruz.</h2><p>${company.intro}</p><p>Kalite yönetim sistemleri, uygunluk değerlendirme ve akreditasyon süreçleri, eğitim ve danışmanlık faaliyetleri ile kalite süreçlerini destekleyen yazılım çözümleri üzerinde çalışıyoruz.</p>${button('BMS’yi tanıyın','/hakkimizda/',true)}</div></div><div class="container quick-links"><a href="/danismanlik/"><span>01</span><h3>Danışmanlık</h3>${arrow}</a><a href="/egitim/"><span>02</span><h3>Eğitim</h3>${arrow}</a><a href="/yazilim/"><span>03</span><h3>Kalite Yazılımları</h3>${arrow}</a></div></section>
 <section class="section pale"><div class="container">${heading('DANIŞMANLIK HİZMETLERİ','Standarttan uygulamaya,<br>her aşamada destek.','Deney ve kalibrasyon laboratuvarlarının yönetim sistemi ve teknik yeterlilik altyapısı için kuruluşa özel çalışmalar.')}${serviceCards()}</div></section>
 <section class="section"><div class="container"><div class="heading-row">${heading('EĞİTİM HİZMETLERİ','Bilgiyi uygulamaya dönüştürün.','Laboratuvarın faaliyet kapsamıyla birlikte planlanan eğitimler.')}${button('Tüm eğitimler','/egitim/',true)}</div>${trainingCards()}<p class="small-note">Eğitimlerin kesin kapsamı, katılımcı sayısı ve süreleri proje başlangıcında netleştirilir.</p></div></section>
 <section class="section navy"><div class="container">${heading('NEDEN BMS?','Laboratuvarınıza özel.<br>Uygulamaya dönük.')}${approachGrid()}</div></section>
 <section class="section"><div class="container">${heading('ÇALIŞMA YAKLAŞIMIMIZ','Planlı bir akreditasyon hazırlığı.')}${process()}${disclaimer()}</div></section>
 <section class="software-strip"><div class="container about-grid"><div><p class="eyebrow">KALİTE YAZILIMLARI</p><h2>İzlenebilir süreçler.<br>Sürdürülebilir iş akışları.</h2></div><div><p>Doküman, kayıt, takip ve raporlama ihtiyaçlarını, uygun olduğunda yazılım destekli iş akışlarıyla ele alıyoruz.</p>${button('Dijitalleşme yaklaşımımız','/yazilim/',true)}</div></div></section>${cta()}`},
 {path:'/hakkimizda/',title:'Hakkımızda',description:'BMS Kalite Yazılım A.Ş., LHUSTEK bünyesinde sağlık, teknoloji ve kalite odaklı danışmanlık, eğitim ve yazılım çalışmaları yürütmektedir.',body:()=>`${pageHero('Hakkımızda','Kalite, sağlık ve teknoloji<br>aynı çatı altında.','Uygulanabilir, sürdürülebilir ve ihtiyaçlara özel çözümler.')}<section class="section"><div class="container about-grid"><div class="about-visual"><img src="/assets/laboratory.png" alt="Laboratuvar çalışmalarını temsil eden mikroskop ve cam malzemeler" width="1536" height="1024"></div><div><h2>BMS Kalite Yazılım A.Ş.</h2><p>${company.intro}</p><p>Kalite yönetim sistemleri, uygunluk değerlendirme ve akreditasyon süreçleri, eğitim ve danışmanlık faaliyetleri ile kalite süreçlerini destekleyen yazılım çözümleri üzerinde çalışıyoruz.</p></div></div><div class="container grid two values"><article><p class="eyebrow">MİSYONUMUZ</p><h2>İhtiyaçlara özel çözümler.</h2><p>${company.mission}</p></article><article><p class="eyebrow">VİZYONUMUZ</p><h2>Sürdürülebilir bir kalite anlayışı.</h2><p>${company.vision}</p></article></div></section><section class="section pale"><div class="container">${heading('YAKLAŞIMIMIZ','Neden BMS?')}${approachGrid()}</div></section>${cta()}`},
 {path:'/danismanlik/',title:'ISO/IEC 17025 Danışmanlık Hizmetleri',description:'Deney ve kalibrasyon laboratuvarları için yönetim sistemi kurulumu, teknik uygulamalar ve TÜRKAK akreditasyonuna hazırlık danışmanlığı.',body:()=>`${pageHero('Danışmanlık','ISO/IEC 17025<br>danışmanlık hizmetleri.','Deney ve kalibrasyon laboratuvarları için yönetim sistemi ve teknik yeterlilik altyapısının kurulması ve geliştirilmesi.')}<section class="section"><div class="container"><div class="jump-links">${services.map(s=>`<a href="#${s.id}">${s.title} ↓</a>`).join('')}</div>${services.map((s,i)=>`<article class="detail-section" id="${s.id}"><div><p class="eyebrow">0${i+1} / DANIŞMANLIK</p><h2>${s.title}</h2><p>${s.short}</p></div>${list(s.items)}</article>`).join('')}${disclaimer()}</div></section><section class="section pale"><div class="container">${heading('PROJE SÜRECİ','Hazırlıktan karar sürecine.')}${process()}<div class="faq"><details><summary>Proje süresi nasıl belirlenir?</summary><p>Proje takvimi; laboratuvarın hazırlık hızı, kapsamın büyüklüğü, metot sayısı, cihaz ve kalibrasyon durumu, yeterlilik testi / laboratuvarlar arası karşılaştırma gereklilikleri ve TÜRKAK planlamasına bağlı olarak değişebilir.</p></details><details><summary>Başvuru ne zaman hazırlanır?</summary><p>Yönetim sistemi ve teknik uygulamaların başvuru için yeterli olgunluğa ulaştığı BMS ve müşteri tarafından birlikte değerlendirildikten sonra başvuru hazırlanır. Güncel TÜRKAK formları, rehberleri ve ek belge talepleri başvuru tarihinde kontrol edilir.</p></details><details><summary>Resmî ücretler hizmet kapsamına dahil midir?</summary><p>TÜRKAK ve diğer resmî kurumların başvuru, inceleme, değerlendirme ve akreditasyon ücretleri danışmanlık hizmet bedeline dahil değildir; müşteri tarafından ayrıca karşılanır.</p></details></div></div></section>${cta()}`},
 {path:'/egitim/',title:'Laboratuvar Eğitimleri',description:'ISO/IEC 17025, iç tetkik, risk, metrolojik izlenebilirlik, metot doğrulama, ölçüm belirsizliği ve kalite kontrol eğitimleri.',body:()=>`${pageHero('Eğitim','Bilgiden uygulamaya,<br>laboratuvar eğitimleri.','Standart ve teknik eğitimleri laboratuvarınızın faaliyet kapsamı ve proje uygulamalarıyla birlikte ele alıyoruz.')}<section class="section"><div class="container">${trainingCards(true)}<aside class="note"><strong>Kuruluşa göre planlanan eğitimler</strong><p>Eğitimlerin kesin kapsamı, personel sayısı ve süreleri proje başlangıcında laboratuvarın faaliyet kapsamına göre netleştirilir. Katılımcılar için e-imzalı eğitim sertifikası düzenlenebilir.</p></aside></div></section>${cta()}`},
 {path:'/yazilim/',title:'Kalite Yazılımları ve Dijitalleşme',description:'Kalite süreçlerinde doküman, kayıt, takip ve raporlama ihtiyaçlarına yönelik BMS yazılım ve dijitalleşme yaklaşımı.',body:()=>`${pageHero('Kalite Yazılımları','Kalite süreçlerinde<br>dijitalleşme perspektifi.','Doküman, kayıt, takip ve raporlama ihtiyaçları için yazılım destekli, sürdürülebilir iş akışları.')}<section class="section"><div class="container"><div class="intro-narrow"><h2>İhtiyaçtan başlayan bir yaklaşım.</h2><p>BMS, kalite süreçlerini destekleyen yazılım çözümleri üzerinde çalışmaktadır. Laboratuvarın ve kuruluşun ihtiyaçları uygun olduğunda doküman, kayıt, takip ve raporlama süreçleri yazılım destekli iş akışlarıyla ele alınabilir.</p></div><div class="grid two values">${[['Doküman ve kayıt','Kalite süreçlerindeki doküman ve kayıt ihtiyaçlarının değerlendirilmesi.'],['Takip ve raporlama','İzlenebilirlik ve süreç takibi ihtiyaçlarının yazılım perspektifiyle ele alınması.']].map(([t,d])=>`<article><p class="eyebrow">DİJİTALLEŞME</p><h2>${t}</h2><p>${d}</p></article>`).join('')}</div></div></section>${cta()}`},
 {path:'/iletisim/',title:'İletişim ve Merkezimiz',description:'BMS Kalite Yazılım A.Ş. merkezi: LHUSTEK, Söğütözü Mahallesi, 9 Eylül Cad. No: 4 İç Kapı No: 1, Ankara.',body:()=>`${pageHero('İletişim','Merkezimiz Ankara’da.','BMS Kalite Yazılım A.Ş. · Lokman Hekim Üniversitesi Sağlık İlaç Teknoloji Merkezi')}<section class="section"><div class="container contact-grid"><div><p class="eyebrow">MERKEZİMİZ</p><h2>Kalite ve teknolojinin<br>buluşma noktasında.</h2><p>${company.center}</p><address>${company.address}</address>${company.email?`<p><a href="mailto:${company.email}">${company.email}</a></p>`:''}${company.phone?`<p><a href="tel:${company.phone.replace(/[^+0-9]/g,'')}">${company.phone}</a></p>`:''}<div class="buttons">${button('Haritada görüntüle','https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(company.address))}<button class="button secondary copy-address" data-address="${company.address}">Adresi kopyala</button></div><p class="copy-status" role="status" aria-live="polite"></p></div><aside class="contact-panel"><span class="location-label">ANKARA / SÖĞÜTÖZÜ</span><h2>LHUSTEK</h2><p>Lokman Hekim Üniversitesi<br>Sağlık İlaç Teknoloji Merkezi</p><div class="contact-divider"></div><p>9 Eylül Caddesi<br>No: 4 · İç Kapı No: 1</p><span class="location-label">BMS KALİTE YAZILIM A.Ş.</span></aside></div></section>`}
];
